apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-selfsigned-cert
  namespace: default
spec:
  secretName: nginx-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - localhost
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster.local
  - nginx.local
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
