apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: default
spec:
  schedule: "0 3 * * *"  # Todo dia às 03:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: bitnami/postgresql:15
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - |
              export PGPASSWORD=$POSTGRES_PASSWORD
              pg_dump -h postgres-sts-0.postgres-service.default.svc.cluster.local -U postgres portfolio > /backups/portfolio-$(date +%Y%m%d-%H%M%S).sql
              find /backups -name "*.sql" -mtime +7 -delete
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            volumeMounts:
            - name: backup-storage
              mountPath: /backups
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            hostPath:
              path: /home/administrator/postgres-backups
              type: DirectoryOrCreate
