apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sts
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-service
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres
      securityContext:
        fsGroup: 70
      initContainers:
      - name: volume-permissions
        image: busybox:1.36
        command:
        - sh
        - -c
        - chown -R 70:70 /var/lib/postgresql/data
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
            add: ["CHOWN", "DAC_OVERRIDE"]
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      containers:
      - name: postgres
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
        envFrom:
        - secretRef:
            name: postgres-secret
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 104Mi
          limits:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 70
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
  updateStrategy:
    type: RollingUpdate
