apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pf-portforward
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pf-portforward-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pf-portforward
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
